github.com:
    git_protocol: ssh
    users:
        ukwhatn:
        yuki-c-watanabe_dena:
    user: yuki-c-watanabe_dena
github.dena.jp:
    git_protocol: ssh
    users:
        yuki-c-watanabe:
    user: yuki-c-watanabe
